#!/bin/bash

CORES=$(grep -c processor /proc/cpuinfo)
CURBRANCH=$(git rev-parse --abbrev-ref HEAD)

# For debugging: create elf files, set sram stack at 0x10001000, set $r0=0
# script read.cfg
if [ -d contrib/loaders/flash/etacorem3 ]
then
	make -j -l${CORES} -C contrib/loaders/flash/etacorem3 $*
	make -j -l${CORES} -C contrib/loaders/flash/etacorem3 \
		read.elf write.elf erase.elf $*
fi
# includes above .inc files
if [ -n "$*" ]
then
	make -j -l${CORES} $*
else
	make -j -l${CORES} DESTDIR=${HOME}/${CURBRANCH} install
	echo "*** Installed to ${HOME}/${CURBRANCH}"
fi
